language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: 55abf0dc-a453-4c0b-ba11-b52f2a9fe1aa
  app: flasktaskrproject6666
  on:
    branch: master
    repo: sheldon66/flasktaskr_project
